package test;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.Month;
import java.util.Calendar;
import java.util.Date;

public class test01 {

    public static void main(String[] args) throws ParseException {
//        Calendar calendar = Calendar.getInstance();
//        System.out.println(calendar);
//        int year=calendar.get(1);
//        System.out.println(year);
//        int year2=calendar.get(Calendar.YEAR);
//        System.out.println(year2);
//        int month=calendar.get(Calendar.MONTH);
//        System.out.println(month);
//        int day=calendar.get(Calendar.DAY_OF_MONTH);
//        System.out.println(day);
        //Calendar calendar = Calendar.getInstance();
//        calendar.set(Calendar.YEAR,2018);
//        calendar.set(Calendar.MONTH,8);
//        calendar.set(Calendar.DAY_OF_MONTH,8);
//        calendar.set(Calendar.HOUR_OF_DAY,8);
//        calendar.set(Calendar.MINUTE,8);
//        calendar.set(Calendar.SECOND,8);
//        calendar.set(Calendar.MILLISECOND,8);
//        calendar.set(2018,8,8,8,8,8);
//        calendar.add(Calendar.YEAR,-1);
//        int year=calendar.get(Calendar.YEAR);
//        int month=calendar.get(Calendar.MONTH);
//        int day=calendar.get(Calendar.DAY_OF_MONTH);
//        int hour=calendar.get(Calendar.HOUR_OF_DAY);
//        int minute=calendar.get(Calendar.MINUTE);
//        int second=calendar.get(Calendar.SECOND);
//        System.out.println(year);
//        System.out.println(month);
//        System.out.println(day);
//        System.out.println(hour);
//        System.out.println(minute);
//        System.out.println(second);
//        Calendar calendar = Calendar.getInstance();
//        calendar.set(Calendar.YEAR, 2008);
//        calendar.set(Calendar.MONTH, Calendar.MAY);
//        calendar.set(Calendar.DAY_OF_MONTH, 12);
//        calendar.set(Calendar.HOUR_OF_DAY, 15);
//        calendar.set(Calendar.MINUTE, 30);
//        calendar.set(Calendar.SECOND, 30);
//        int year = calendar.get(Calendar.YEAR);
//        int month = calendar.get(Calendar.MONTH);
//        int day = calendar.get(Calendar.DAY_OF_MONTH);
//        int hour = calendar.get(Calendar.HOUR_OF_DAY);
//        int minute = calendar.get(Calendar.MINUTE);
//        int second = calendar.get(Calendar.SECOND);
//        System.out.println(year);
//        System.out.println(month+1);
//        System.out.println(day);
//        System.out.println(hour);
//        System.out.println(minute);
//        System.out.println(second);
//        Date date = new Date();
//        date.setYear(year-1900);
//        date.setMonth(month);
//        date.setDate(day);
//        date.setHours(hour);
//        date.setMinutes(minute);
//        date.setSeconds(second);
//        System.out.println(date);
//        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss SSS");
//        String str=sdf.format(date);
//        System.out.println(str);
//        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
//        String str="2008-05-12 15:30:30";
//        Date date=new Date();
//        date=sdf.parse(str);
//        System.out.println(date);
//        Calendar cld=Calendar.getInstance();
//        cld.setTime(date);
//        System.out.println(cld.get(Calendar.YEAR));
//        System.out.println(cld.get(Calendar.MONTH)+1);
//        System.out.println(cld.get(Calendar.DAY_OF_MONTH));
//        System.out.println(cld.get(Calendar.HOUR_OF_DAY));
//        System.out.println(cld.get(Calendar.MINUTE));
//        System.out.println(cld.get(Calendar.SECOND));
//        cld.set(Calendar.SECOND,56);
//        Date time=cld.getTime();
//        String str1=sdf.format(time);
//        System.out.println(str1);
//        LocalDateTime now = LocalDateTime.now();
//        System.out.println(now);
//        LocalDateTime z=LocalDateTime.of(2018, 9, 23, 23, 23);
//        System.out.println(z);
//        LocalDateTime localDateTime=z.plusYears(1).plusSeconds(1);
//        System.out.println(localDateTime);
////        int year=localDateTime.getYear();
////        System.out.println(year);
//        LocalDateTime ldt=z.minusYears(2);
//        System.out.println(ldt);
//        long ll=System.currentTimeMillis();
//        System.out.println(ll);
        
    }
}